#  setting of repo ==> secrets ==> action ==> new repo secret

# actions/setup-python@v4    ===>  write python code present in repo


name: For secret Messsage
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python checkpyt.py

      - name: Run a one-line script
      # HOW TO WRITE SECRET
        run: echo ${{ secrets.MESSAGE }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
